name: gemini_vision
description: "Prototype vision app backed up with Gemini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  image: ^4.5.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
